PREFIX sch: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?school ?lattitude ?longitude ?url ?name ?website WHERE {
  ?school rdf:type sch:School;
        sch:containedInPlace <city-uri>;
        sch:lattitude ?lattitude;
        sch:longitude ?longitude;
        sch:name ?name;
        sch:url ?url;
        sch:identifier ?website.
}