PREFIX schema: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?latitude ?longitude ?url ?name ?wikidataEntityId WHERE {
  <city-uri> schema:latitude ?latitude;
        schema:longitude ?longitude;
        schema:name ?name;
        schema:url ?url;
        schema:identifier ?wikidataEntityId.
}