PREFIX schema: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?school ?latitude ?longitude ?url ?name ?website WHERE {
  ?school rdf:type schema:School;
        schema:containedInPlace <city-uri>;
        schema:latitude ?latitude;
        schema:longitude ?longitude;
        schema:name ?name;
        schema:url ?url;
        schema:identifier ?website.
}